== Family of Johann Konrad and Katharina Daehler

* JOHANN KONRAD DAEHLER
  b: 6 Feb., 1811, Freienseen, Hesse-Darmstadt
  d: 16 June, 1897, Fair Haven Township, Illinois
  m: 8 Aug., 1838, Freienseen, Hesse-Darmstadt
  KATHARINA JUNG
  b: 22 May, 1813, Freienseen, Hesse-Darmstadt
  d: 7 Oct., 1888, Fair Haven Township, Illinois

** HENRY JACOB DAEHLER
   b: 9 Nov., 1839, Freienseen, Hesse-Darmstadt
   d: 11 April, 1910, Chadwick, Illinois
   m: 17 Dec., 1859, Fair Haven Township, Illinois
   [[family-HJD-EZ]]
   ELISA ZUGSCHWERDT
   b: 22 March, 1842, Sellenrod, Hesse
   d: 27 March, 1865, Fair Haven Township, Illinois
   m: 14 Feb., 1868, Fair Haven Township, Illinois
   [[family-HJD-WFSH]]
   WILHELMINA FREDERICKA SOPHIA HEYER
   b: 14 Dec., 1840, Daberkow, Brandenburg
   d: 25 April, 1915, Fair Haven Township, Illinois

** CHRISTIANA DAEHLER
   b: 20 Jan., 1841, Freienseen, Hesse-Darmstadt
   d: 16 May, 1841, Freienseen, Hesse-Darmstadt

** LOUIS CHRISTIAN DAEHLER
   b: 26 May, 1842, Freienseen, Hesse-Darmstadt
   d: 21 Dec., 1907, Fair Haven Township, Illinois
   m: 7 April, 1872, Fair Haven Township, Illinois
   ANNA ELISA HARTMAN
   b: 20 Feb., 1853, Golzenhein, Hesse-Darmstadt
   d: 20 Dec., 1924, Chadwick, Illinois

** WILHELMINA DAEHLER
   b: 3 Aug., 1844, Freienseen, Hesse-Darmstadt
   d: 16 April, 1901, Columbus, Ohio
   m: 4 March, 1866, Fair Haven Township, Illinois
   OTTO IMMELT
   b: 13 Feb., 1832, Freienseen, Hesse-Darmstadt
   d: 24 Nov., 1897, Waterloo, Iowa

** FREDERICK DAEHLER
   b: 20 Oct., 1846, Freienseen, Hesse-Darmstadt
   d: 20 Oct., 1846, Freienseen, Hesse-Darmstadt

** still born daughter
   b: 17 Feb., 1848, Freienseen, Hesse-Darmstadt
   d: 17 Feb., 1848, Freienseen, Hesse-Darmstadt

[[root-family-HJD-EZ]]
=== Children of Henry Jacob and Elisa Daehler

* DOROTHEA DAEHLER
  b: 4 April, 1860, Fair Haven Township, Illinois
  d: 8 May, 1939, Mec Cool Junction, Nebraska
  m: 24 Feb., 1879, Fair Haven Township, Illinois
  CHARLES SMITH
  b: 10 July, 1851, Asel, Hesse-Darmstadt
  d: 23 Nov., 1897, Mc Cool Junction, Nebraska

* LOUIS CHRISTIAN DAEHLER
  b: 3 March, 1862, Fair Haven Township,
  d: 14 Jan., 1908, Fair Haven Township,
  m: 2 July, 1884, East Jordan, Illinois
  LUCINDA MARY ZINNEL
  b: 13 April, 1866, Fair Haven Township, Illinois
  d: 30 March, 1892, Chicago, Illinois

* KATHARINA DAEHLER
  b: 10 May, 1863, Fair Haven Township, Illinois
  d: 28 March, 1946, Chadwick, Illinois
  m: 26 Dec., 1880, Fair Haven Township, Illinois
  CHRISTIAN STRAUB
  b: 14 May, 1852, Snyder County, Pennsylvania
  d: 20 June, 1935, Chadwick, Illinois

* ELISA WILHELMINA DAEHLER
  b: 27 March, 1865, Fair Haven Township, Illinois
  d: 9 March, 1919, Elgin, Illinois
  m: 9 Nov., 1887, Fair Haven Township, Illinois
  AUGUST CARL GELDMACHER
  b: 26 May, 1864, Fair Haven Township, Illinois
  d: 19 Sept., 1944, Elgin, Illinois

[[root-family-HJD-WFSH]]
=== Children of Henry Jacob and Wilhelmina Daehler

* HENRY JACOB DAEHLER
  b: 28 Jan., 1869, Fair Haven Township, Illinois
  d: 13 March, 1961, Sterling, Illinois
  m: 24 Feb., 1904, Fair Haven Township, Illinois
  KATHERINE KEIL
  b: 17 Oct., 1879, Fair Haven Township, Illinois
  d: 20 Aug., 1952, Chadwick, Illinois

* WILLIAM CHRISTIAN DAEHLER
  b: 15 Aug., 1870, Fair Haven Township, Illinois
  d: 15 March, 1964, Spring Valley, Minnesota
  m: 10 July, 1894, Mt. Carroll, Illinois
  ANNA KATHRYN SCHREINER
  b: 18 Feb., 1874, Mt. Carroll, Illinois
  d: 11 Nov., 1948, Waterloo, Iowa

* ANNA MARIA DAEHLER
  b: 13 July, 1872, Fair Haven Township, Illinois
  d: 28 April, 1902, Fair Haven Township, Illinois
  m: 17 Jan., 1894, Fair Haven Township, Illinois
  CHARLES J. QUECKBOERNER
  b: 3 Aug., 1870, Fair Haven Township, Illinois
  d: 20 Feb., 1948, Fair Haven Township, Illinois

* CONRAD JOHN DAEHLER
  b: 5 May, 1874, Fair Haven Township, Illinois
  d: 9 June, 1953, Sterling, Illinois
  m: 10 Feb., 1910, Cherry Grove, Illinois
  HAZEL ETHRIDGE
  b: 27 Nov., 1885, Carroll County, Illinois
  d: 7 May, 1971, Morrison, Illinois

* LOUISE DAEHLER
  b: 15 Aug., 1876, Fair Haven Township, Illinois
  d: 20 April, 1877, Fair Haven Township, Illinois

* EMMA DAEHLER
  b: 10 May, 1878, Fair Haven Township, Illinois
  d: 28 April, 1966, Morrison, Illinois
  m: 5 Feb., 1902, Fair Haven Township, Illinois
  CONRAD GEISZ
  b: 12 March, 1872, Fair Haven Township, Illinois
  d: 25 July, 1943, Chadwick, Illinois

[[stop]]
==== Descendants of Charles and Dorothea Smith

* WILLIAM HENRY ADAM SMITH
  b: 10 March, 1880, Fair Haven Township, Illinois
  d: 6 Jan., 1966, Exeter, Nebraska
  m: 13 Jan., 1904, Exeter, Nebraska
  MARTHA ELIZABETH MILLER
  b: 2 Feb., 1883, Coleta, Illinois
  d: 24 March, 1964, Friend, Nebraska

* LOUIS WILLIAM SMITH
  b: 23 April, 1881, Chadwick, Illinois
  d: 6 June, 1952, Exeter, Nebraska
  m: 13 Oct., 1905, Mc Cool Junction, Nebraska
  PEARL V. CUDABACK
  b: 16 July, 1887, Mc Cool Junction, Nebraska
  d: 27 July, 1967, Whittier, California

* LOUISE BERTHA SMITH
  b: 20 Aug., 1883, Audubon County, Iowa
  d: 12 Nov., 1946, York, Nebraska
  m: 7 Feb., 1904, Mc Cool Junction, Nebraska
  HENRY PHILIP SMITH
  b: 7 Oct., 1876, Hatsbach, Germany
  d: 1 Aug., 1945, Bradshaw, Nebraska

** HILMA ELIZABETH SMITH
   b: 18 Dec., 1904, Me Cool Junction, Nebraska
   d: 23 Oct., 1974, York, Nebraska
   m: 9 March, 1927, Me Cool Junction, Nebraska
   HAROLD STEWART NORQUEST
   b: 15 March, 1901, York, Nebraska
   d: 16 March, 1957, York, Nebraska

*** MARCELLA MAE NORQUEST
    b: 10 May, 1928, York, Nebraska
    m: 8 June, 1947, Mc Cool Junction, Nebraska
    KENNETH MC LAIN
    b: 27 Aug., 1924, York, Nebraska

**** RICHARD MERLE MC LAIN
     b: 5 May, 1949, York, Nebraska
     m: 7 June, 1969, Hampton, Nebraska
     LOIS ANN HEIDEN
     b: 10 Dec., 1948, York, Nebraska

***** ANGELA CHRISTINE MC LAIN
      b: 5S Nov., 1969, Lincoln, Nebraska

***** BRENDA JENEINE MC LAIN
      b: 8 Dec., 1972, Dumas, Texas

**** MILTON GENE MC LAIN
     b: 15 April, 1952, York, Nebraska
     m: 13 June, 1971, York, Nebraska
     LINDA KAY MC GREW
     b: 9 Feb., 1952, Macomb, Illinois

***** STACIE LYNN MC LAIN
      b: 24 Nov., 1971, Amarillo, Texas

*** DELBERT LELAND NORQUEST
    b: 2 Aug., 1930, York, Nebraska
    m: 26 April, 1953, McCool Junction, Nebraska
    MARGERY RAY GREUTER
    b: 26 May, 1934, Hastings, Nebraska

**** JANALEE NORQUEST
     b: 11 Sept., 1956, York, Nebraska

**** KENT STEWART NORQUEST
     b: 11 June, 1959, Hastings, Nebraska

*** BURTON GENE NORQUEST
    b: 17 Feb., 1935, York, Nebraska
    m: 30 March, 1958, Mc Cool Junction, Nebraska
    NANCY RANEE CRAMER
    b: 20Dec., 1938, Loup City, Nebraska

**** BILLY GENE NORQUEST
     b: 18 March, 1959, York, Nebraska

**** LYNN ANN NORQUEST
     b: 9 April, 1962, York, Nebraska

**** LARRY ALLEN NORQUEST
     b: 9 April, 1962, York, Nebraska

**** JEFF HAROLD NORQUEST
     b: 25 Dec., 1967, York, Nebraska

** CLARA MAE SMITH
   b: 5 May, 1908, Me Cool Junction, Nebraska
   d: 29 Nov., 1973, Lincoln, Nebraska
   m: 13 July, 1936, Cheyenne, Nebraska
   MERVIN JAMES MCGILL
   b: 26 April, 1904, Garland, Nebraska
   d: 6 July, 1968, Lincoln, Nebraska

*** JAMES HENRY MCGILL
    b: 28 June, 1939, Lincoln, Nebraska
    m: 1 May, 1959, Yutan, Nebraska
    MARY ANNE LARLOFF
    b: 27 Nov., 1939, Omaha, Nebraska

**** LORI ANN MCGILL
     b: 15 Aug., 1960, Omaha, Nebraska

**** JEFFREY JAMES MCGILL
     b: 2 Nov., 1962, Omaha, Nebraska

**** LIESA GAYE MCGILL
     b: 28 Jan., 1964, Lincoln, Nebraska

**** LYNETTE KRISTEN MCGILL
     b: 4 Sept., 1968, Omaha, Nebraska

*** DANIEL LEROY MCGILL
    b: 10 July, 1942, Lincoln, Nebraska
    m: 25 March, 1961, Council Bluffs, Iowa
    IOLA KAY TWIFORD
    b: 23 Nov., 1943, Rosalie, Nebraska

**** SHERRI LYNN MCGILL
     b: 14 Oct., 1961, Fort Collins, Colorado

**** SUZANNE KAY MCGILL
     b: 1 March, 1964, Lincoln, Nebraska

** DOROTHEA ALMA GRACE SMITH
   b: 21 May, 1912, Mc Cool Junction, Nebraska
   d: 15 April, 1975, Fort Collins, Colorado
   m: 4 June, 1933, Mc Cool Junction, Nebraska
   JOHN ANTON SHIMONEK
   b: 20 May, 1908, Wilber, Nebraska

*** DOTTIE JO ANN SHIMONEK
    b: 12 Sept., 1934, Ewing, Nebraska
    m: 18 April, 1957, Ashland, Nebraska
    ROY ELBERT SCHIEFELBEIN
    b: 16 Oct., 1930, New Understood, South Dakota

**** NANCY JO SCHIEFELBEIN
     b: 31 July, 1962, St. Louis, Missouri

*** GARY JOHN SHIMONEK
    b: 28 Nov., 1944, Fremont, Nebraska
    m: 4 Dec., 1965, Denver, Colorado DIV. 1970
    CHARLENE RAE SIMMA
    m: 14 July, 1973, Denver, Colorado
    MARY ANNE BOURRET
    b: 2 Nov., 1950, Minneapolis, Minnesota

* CLARA MINNA FREDERICKA SMITH
  b: 20 Dec., 1886, Audubon County, Iowa
  d: 8 April, 1946, York, Nebraska
  m: 6 Feb., 1907, Mc Cool Junction, Nebraska
  ROBERT WILLIAM YOUNG
  b: 24 Sept., 1878, Morrison, Illinois
  d: 29 March, 1961, Geneva, Nebraska

** still born son
   b: 17 Aug., 1908, Me Cool Junction, Nebraska

** BOYD OLIVER YOUNG
   b: 9 March, 1912, Mc Cool Junction, Nebraska
   m: 30 Dec., 19836, Me Cool Junction, Nebraska
   ALBERTA ERNESTINE KLONE
   b: 26 May, 1912, Mc Cool Junction, Nebraska

*** RICHARD LOWELL YOUNG
    b: 15 Nov., 1937, York, Nebraska
    m: 6 Jan., 1967, Aurora, Colorado
    DAWN GONYE BLEI
    b: 9 Dec., 1937, York, Nebraska

*** LINDA LORENE YOUNG
    b: 17 March, 1937, York, Nebraska
    m: 31 May., 1959, York, Nebraska
    CLAUDE EUGENE BAILEY
    b: 29 Aug., 1934, York, Nebraska

**** TIMOTHY BAILEY
     b: 18 April, 1960, York, Nebraska

**** TERRY BAILEY
     b: 23 May., 1961, York, Nebraska

**** KYLE BAILEY
     b: 24 June, 1966, York, Nebraska

*** PHYLIS KAY YOUNG
    b: 11 Oct., 1946, York, Nebraska
    m: 6 March, 1971, Me Cool Junction, Nebraska
    NEIL ALLEN WEST
    b: 21 Oct., 1947, Seward, Nebraska

**** BRIAN CARL WEST
     b: 30 June, 1973, York, Nebraska

** HELEN ONITA YOUNG
   b: 28 Feb., 1920, Me Cool, Junction, Nebraska
   m: 28 June, 1941, Las Vegas, Nevada
   RICHARD ELWOOD HAGER
   b: 1 Nov., 1919, Fairmont, Nebraska

*** DENNIS GERALD HAGER
    b: 26 July, 1942, Los Angeles, California
    m: 15 Aug., 1965, Columbus, Ohio
    LINDA LEE. CARPENTER
    b: 20 Jan., 1946, Columbus, Ohio

**** TISHIA DAWN HAGER
     b: 1 May, 1969, Columbus, Ohio

*** VIRGIL LEE HAGER
    b: 24 Jan., 1950, York, Nebraska
    m: 1 Oct., 1967, Me Cool Junction, Nebraska
    PATRICIA ANN MILLER
    b: 10 Aug., 1950, York, Nebraska

**** KARRY ANN HAGER
     b: 3 Feb., 1968, York, Nebraska

*** MACHELL LEE HAGER
    b: 21 Feb., 1972, Columbus, Ohio

*** ROLAND DEAN HAGER
    b: 11 Aug., 1954, York, Nebraska

* LENA HENRIETTA SMITH
  b: 4 March, 1889, Audubon County, Iowa
  d: in infancy

==== Descendants of Louis C. and Lucinda M. Daehler

* ALVIN AUGUST DAEHLER
  b: 12 May, 1885, Chadwick, Illinois
  d: 8 May, 1964, Santa Cruz, California
  m: 25 Dec., 1910, Milledgeville, Illinois
  DAISY MARTHA DERR
  b: 24 March, 1885, Milledgeville, Illinois
  d: 22 Aug., 1936, Clinton, Iowa

** LEO ERNEST DAEHLER
   b: 8 July, 1912, Chicago, Illinois
   m: 25 Dec., 1936, Clinton, Iowa DIV.
   MILDRED ELIZABETH TILLOTSON
   b: 20 April,1915, Washington, Iowa
   m: 9 Dec., 1946, Des Moines, Iowa
   MOYA GLADYS COOK
   b: 10 April, 1920, Goulburn, N.S.W., Australia

*** RICHARD ALLEN DAEHLER
    b: 17 Jan., 1938, Clinton, Iowa
    m: 26 June, 1956, Clinton, Iowa DIV.
    JANICE GRELL
    m: 15 June, 1968, Clinton, Iowa
    KAY JOAN ALBRIGHT
    b: 2 April, 1948

**** KIMBERLY ANN DAEHLER
     b: 12 Jan., 1957, De Witt, Iowa

**** KRISTA KAY DAEHLER
     b: 23 Oct., 1958, Clinton, Iowa

**** KURT ALLAN DAEHLER
     b: 19 Dec., 1959, Clinton, Iowa

*** THOMAS GEORGE DAEHLER
    b: 7 Dec., 1941, Milwaukee, Wisconsin
    m: 6 June, 1962, Clinton, Iowa
    MARIETTA MAY WILLIAMS
    b: 7 May, 1941

**** KEITH ALLEN DAEHLER
     b: 1 May, 1966, Indianapolis, Indiana

**** KATHERINE MARIE DAEHLER
     b: 21 Aug., 1969, Indianapolis, Indiana

*** JACQUELINE MOYA DAEHLER
    b: 10 July, 1951, Milwaukee, Wisconsin

*** WILLIAM FREDERICK LEO DAEHLER
    b: 24 June, 1953, Milwaukee, Wisconsin

* LEO HENRY DAEHLER
  b: 28 Jan., 1887, Chadwick, Illinois

==== Descendants of Christian and Katharina Straub

* ANNA ISABELLE STRAUB
  b: 19 May, 1882, Fair Haven: Township
  m: 20 Dec., 1902, Chadwick, Illinois
  WILLIAM LEWIS
  b: 26 Feb., 1879, Peoria, Kansas
  d: 10 Nov., 1952, Dixon, Illinois

** CECIL ADELBERT LEWIS
   b: 8 May, 1904, Chadwick, Illinois
   d: 5 March, 1921, Dixon, Illinois

** KATHRYN LAURA LEWIS
   b: 8 May, 1909, Chadwick, Illinois
   m: 21 Dec., 1929, Chicago, Illinois
   PAUL HENNING HANSON
   b: 19 Oct., 1898, Olsberg, Kansas
   d: 7 Jan., 1963, Sarasota, Florida
   m: 12 Nov., 1966, Sarasota, Florida
   ELMER EARL IKERMAN
   b: 8 Oct., 1901, Warren, Ohio

*** BEVERLY CECILE HANSON
    b: 7 Oct., 1934, Chicago, Illinois
    m: 29 April, 1955, Sarasota, Florida
    HOWARD HALL BAREFOOT
    b: 26 March, 1928, Braddock, Pennsylvania

**** ALAN REED BAREFOOT
     b: 15 July, 1956, Sarasota, Florida

**** BRADLEY PAUL BAREFOOT
     b: 4 Dec., 1957, Sarasota, Florida

**** STEVEN NEAL BAREFOOT
     b: 15 Sept., 1960, Sarasota, Florida

** CHARLES EDGAR LEWIS
   b: 25 Nov., 1911, Chadwick, Illinois
   d: 24 Dec., 1972, Morrison, Illinois
   m: 14 Sept., 1935, Stillman Valley, Illinois
   RITA MAC ROBERTS
   b: 13 July, 1915, Chana, Illinois

*** JUDITH RAE LEWIS
    b: 21 March, 1937, Kansas City, Missouri
    m: 1 Sept., 1955, Fair Haven Township, Illinois
    RAYMOND LA VERN ADOLPH
    b: 19 Oct., 1936, Fair Haven Township, Illinois

**** TIM SCOTT ADOLPH
     b: 10 May, 1958, Sterling, Illinois

**** DAVID ERIC ADOLPH
     b: 5 Dec., 1963, Morrison, Illinois

* WILLIAM FRANKLIN STRAUB
  b: 25 Jan., 1884, Fair Haven Township, Illinois
  d: 16 Sept., 1950, Rockford, Illinois
  m: 10 Nov., 1910, Freeport, Illinois
  ELIZABETH LILY LARKEY
  b: 17 Aug., 1883, Coleta, Illinois
  d: 4 Oct., 1970, Morrison, Illinois

** LYLE CLARKE STRAUB
   b: 23 March, 1919, Chadwick, Illinois
   m: 18 Jan., 1947, Rockford, Illinois
   EVELYN MARGARET BOYLE
   b: 27 Nov., 1921, Milwaukee, Wisconsin

*** GERALD WILLIAM STRAUB
    b: 9 Oct., 1951, Rockford, Illinois

*** DENNIS JOHN STRAUB
    b: 18 Jan., 1959, Rockford, Illinois

* CLARA LOUISA STRAUB
  b: 16 June, 1889, Fair Haven Township, Illinois
  d: 27 Feb., 1971, Mendota, Illinois
  m: 7 Sept., 1909, Freeport, Illinois
  DONALD DAVID CLARKE
  b: 30 Jan., 1892, Downers Grove, Illinois
  d: 7 Aug., 1968, Van Orin, Illinois

** ORVILLE RAYMOND CLARKE
  b: 24 June, 1910, Chadwick, Illinois
  m: 10 Sept., 1940, Memphis, Tennessee
  SARAH LOUISE WATSON
  b: 13 April, 1915, Troy, Tennessee

*** JACK DONALD CLARKE
    b: 12 Nov., 1944, Ripon, Wisconsin
    m: 17 Nov., 1961, Ripon, Wisconsin
    PHYLLIS ANN HYDE
    b: 18 Oct., 1942, Ripon, Wisconsin

**** TODD JEFFREY CLARKE
     b: 5 Aug., 1962, Ripon, Wisconsin

**** KATHLEEN JANE CLARKE
     b: 29 July, 1964, Fond du Lac, Wisconsin

**** KRISTINE ANN CLARKE
     b: 21 July, 1966, Ripon, Wisconsin

*** JEFFREY ORVILLE CLARKE
    b: 18 June, 1947, Ripon, Wisconsin
    m: 7 Sept., 1968, Ripon, Wisconsin
    GAIL ANN HARMS
    b: 31 Aug., 1947, Ripon, Wisconsin

**** MELISSA RENEE CLARKE
     b: 30 Nov., 1971, Wausau, Wisconsin

*** JANE LOUISE CLARKE
    b: 18 June, 1947, Ripon, Wisconsin
    d: 21 June, 1947, Ripon, Wisconsin

*** JAY NEWTON CLARKE
    b: 9 April, 1951, Ripon, Wisconsin
    m: 24 July, 1971, Ripon, Wisconsin
    HOLLY ANN HAMMEN
    b: 3 Jan., 1952, Ripon, Wisconsin

*** JANE WATSON CLARKE
    b: 12 June, 1953, Ripon, Wisconsin
    m: 7 July, 1973, Ripon, Wisconsin
    GARY MARLAND PAGE
    b: 6 May, 1950, Ripon, Wisconsin

** LA VERE HARRY CLARKE
   b: 18 March, 1913, Chadwick, Illinois
   m: 29 Dec., 1941, Peoria, Illinois
   LOIS PHALEN
   b: 29 Dec., 1915, Sterling, Illinois

*** SANDRA JANINE CLARKE
    b: 26 March, 1947, Mendota, Illinois
    m: 11 June, 1966, Peoria, Illinois
    LYNN HAROLD STEWART
    b: 13 March, 1943, Fulton, New York
    m: 5 May, 1973, Peoria, Illinois
    JOSEPH ROBERT MILLS
    b: 6 Feb., 1945, Peoria, Illinois

**** LISA JOANN STEWART
     b: 30 Jan., 1967, Stevens Point, Wisconsin

**** AARON MARK STEWART
     b: 12 Sept., 1969, Milwaukee, Wisconsin

*** JOY ANN CLARKE
    b: 15 Nov., 1949, Mendota, Illinois
    m: 19 Sept., 1970, Peoria, Illinois
    CARL B. HENDERSON
    b: 3 July, 1947, Marion, Indiana

** IONE ALICE CLARKE
   b: 29 Sept., 1914, Chadwick, Illinois
   m: 23 April, 1937, Chicago, Illinois
   JULIUS JAMES BUCHANAN
   b: 20 Sept., 1913, Redgranite, Wisconsin

*** LAWRENCE JAMES BUCHANAN
    b: 31 March, 1939, Mendota, Illinois
    d: 19 March, 1964, Denver, Colorado
    m: 18 July, 1958, Denver, Colorado
    BARBARA ANN BACON
    b: 15 March, 1940, Denver, Colorado

**** REBECCA ANN BUCHANAN
     b: 18 May, 1959, Denver, Colorado

*** BONNIE JEAN BUCHANAN
    b: 4 May, 1941, Mendota, Illinois
    m: 1 Nov., 1959, Pine, Colorado DIV.
    GEORGE HOWARD DUNHAM
    b: 23 May, 1930, Denver, Colorado
    m: 19 Aug., 1974, Pittsburgh, Pennsylvania
    WILLIAM DAMIANO
    b: 17 Feb., 1934, Pittsburgh, Pennsylvania

**** TIMOTHY DON DUNHAM
     b: 12 June, 1961, Denver, Colorado

**** ANDREW LEE DUNHAM
     b: 12 April, 1963, Denver, Colorado

*** HEATHER KAY BUCHANAN
    b: 4 Feb., 1944, Denver, Colorado
    m: 1 Nov., 1963, Durango, Colorado DIV.
    DARREL SMYTH
    m: 5 Sept., 1965, Williston, North Dakota
    SYD FLEXHAUG
    b: 3 Dec., 1933, Williston, North Dakota

**** STACY LEE SMYTH
     b: 21 Aug., 1964, Denver, Colorado

**** GALYN HAROLD FLEXHAUG
     b: 23 July, 1966, Denver, Colorado

*** CLARKE EDWARD BUCHANAN
    b: 19 July, 1947, Mendota, Illinois
    m: 19 Aug., 1964, Indian Hills, Colorado
    NANCY LOUISE SINDT
    b: 19 June, 1947, Denver, Colorado
    m: 28 Aug., 1971, Colorado Springs, Colorado
    KATHRYN LEE PIERCE
    b: 1 June, 1953, Kingsville, Texas

**** LARRY RICHARD BUCHANAN
     b: 13 Feb., 1965, Denver, Colorado

*** JOHN ARNOLD BUCHANAN
    b: 24 Nov., 1952, Denver, Colorado

*** ELIZABETH ANNE BUCHANAN
    b: 27 May, 1954, Denver, Colorado
    m: 8 June, 1974, Indian Hills, Colorado
    RANDALL WARREN CLARK
    b: 27 Nov., 1953, Poplar Bluff, Missouri

** EVAN MONROE CLARKE
   b: 18 Sept., 1916, Chadwick, Illinois

** MYRENE ISABELLE CLARKE
   b: 13 July, 1918, Chadwick, Illinois
   m: 7 Sept., 1939, Mendota, Illinois
   LOUIS PATRICK ROTH
   b: 7 Jan., 1907, Chicago, Illinois

*** DAVID LOUIS ROTH
    b: 31 Dec., 1941, Chicago, Illinois
    m: 16 Oct., 1960, Princeton, Illinois
    JUDITH ELAINE SAPP
    b: 8 Feb., 1941, Princeton, Illinois

**** STEVEN KENT ROTH
     b: 7 May, 1961, Princeton, Illinois

**** CHRISTINE ANNE ROTH
     b: 13 April, 1963, Princeton, Illinois

**** KELLY ELAINE ROTH
     b: 31 Jan., 1965, Princeton, Illinois

**** MICHAEL DAVID ROTH
     b: 28 Aug., 1969, Leon, Iowa

*** MICHAEL GORDON ROTH
    b: 27 Nov., 1943, Chicago, Illinois
    m: 2 Aug., 1964, Princeton, Illinois
    MARIE KATHLEEN ANTHONY
    b: 20 Sept., 1946, Princeton, Illinois

**** WILLIAM MICHAEL ROTH
     b: 5S Jan., 1965, Ames, Iowa

**** JAMES ANTHONY ROTH
     b: 24 Dec., 1968, Kansas City, Missouri

*** PATRICIA KAY ROTH
    b: 12 Feb., 1956, Chicago, Illinois

** ARNOLD LINCOLN CLARKE
   b: 13 Feb., 1921, Chadwick, Illinois
   m: 10 June, 1950, Somonauk, Illinois
   PATRICIA LA BOLLE
   b: 17 March, 1918, Somonauk, Illinois

* MELVIN CONRAD STRAUB
  b: 1 Nov., 1896, Fair Haven Township, Illinois
  m: 19 Dec., 1933, Galena, Illinois
  DOROTHY ELTHEDA FERRIS
  b: 13 May, 1905, Whiteside County, Illinois
  d: 28 Oct., 1966, Sterling, Illinois

** MARJORIE JOYCE STRAUB
   b: 6 Sept., 1936, Freeport, Illinois
   m: 23 April, 1970, Lake Forest, Illinois
   JAMES ROBERT GLACKING
   b: 23 April, 1928, Waterman, Illinois

** JOHN LOUIS STRAUB
   b: 22 Jan., 1938, Freeport, Illinois
   m: 17 July, 1956, Holly Springs, Mississippi
   ARVILLA ROSE KELLER
   b: 3 Feb., 1939, Fair Haven Township, Illinois

*** MICHAEL JOHN STRAUB
    b: 2 Sept., 1960, Morrison, Illinois

*** CHRISTINE ANNE STRAUB
    b: 3 Jan., 1964, Morrison, Illinois

*** MARK LOUIS STRAUB
    b: 20 Aug., 1967, Morrison, Illinois

==== Descendants of August C. and Elisa W. Geldmacher

* WALTER CARL GELDMACHER
  b: 25 April, 1888, Chadwick, Illinois
  d: 4 Nov., 1964, Elgin, Illinois
  m: 16 April, 1913, Kiester, Minnesota
  EMMA M. GEORS
  b: 27 Dec., 1891, Dundee, Illinois

** ROBERT CARL GELDMACHER
   b: 22 April, 1917, Elgin, Illinois
   m: 27 Sept., 1941, St. Charles, Illinois
   THERESA SWANBERG
   b: 23 March, 1921, St. Charles, Illinois

*** ANN MARIE GELDMACHER
    b: 26 June, 1942, De Kalb, Illinois
    m: 14 Sept., 1968, Hoboken, New Jersey
    PETER ALICANDRI
    b: 1 Dec., 1936, Brooklyn, New York

**** ANDREW ROBERT ALICANDRI
     b: 10 March, 1970, Brooklyn, New York

**** VICTORIA THERESE ALICANDRI
     b: 13 Feb., 1974, Hoboken, New Jersey

*** CECILY LOUISE GELDMACHER
    b: 24 Jan., 1946, Lafayette, Indiana

*** MARY ELLEN GELDMACHER
    b: 14 June, 1947, Lafayette, Indiana

** RALPH RUSSELL GELDMACHER
   b: 17 Sept., 1918, Elgin, Illinois
   m: 20 Dec., 1945, Milton, Massachusetts
   MARILYN CRUCHSHANK
   b: 14 Nov., 1922, Milton, Massachusetts

*** RALPH RUSSELL GELDMACHER
    b: 30 Sept., 1949, Milton, Massachusetts
    m: 14 Aug., 1971, Milton, Massachusetts
    DIANE ONEIL
    b: 12 March, 1950, Milton, Massachusetts

**** MELLISSA AMY GELDMACHER
     b: 12 Nov., 1974, Milton, Massachusetts

**** RALPH RUSSELL GELDMACHER
     b: 10 Nov., 1978, Boston, Massachusetts
     m: 29 May, 2010, Halifax, Massachusetts
     GEMMA MERLE SANDERS
     b: 22 Dec., 1979, Brisbane, Queensland, Australia

***** VIVIAN JOAN GELDMACHER
      b: 24 Apr., 2014, Weymouth, Massachusetts

*** CHRISTOPHER ALAN GELDMACHER
    b: 9 May, 1951, Milton, Massachusetts

*** SARAH JANE GELDMACHER
    b: 23 Nov., 1952, Milton, Massachusetts

*** PETER WALTER GELDMACHER
    b: 25 Oct., 1955, Milton, Massachusetts

** RUSSELL LLOYD GELDMACHER
   b: 30 Aug., 1927, Elgin, Illinois
   m: 19 June, 1954, Elgin, Illinois
   CATHERINE SCHMITENDORF
   b: 30 Nov., 1933, Elgin, Illinois

*** JAY LINDSEY GELDMACHER
    b: 21 Oct., 1955, Kansas City, Kansas

*** CATHY ANN GELDMACHER
    b: 2 May, 1958, Kansas City, Kansas

*** LISA MARY GELDMACHER
    b: 26 May, 1962, Kansas City, Kansas

*** THOMAS RUSSELL GELDMACHER
    b: 4 June, 1970, Elgin, Illinois

** DONALD EUGENE GELDMACHER
   b: 21 March, 1929, Elgin, Illinois
   m: 1 Sept., 1956, Elgin, Illinois
   BEVERLY ANN BROCKNER
   b: 6 May, 1931, Elgin, Illinois

*** KAREN JEAN GELDMACHER
    b: 26 March, 1958, Elgin, Illinois

*** KURT WALTER GELDMACHER
    b: 10 March, 1960, Elgin, Illinois

*** KRIS ANN GELDMACHER
    b: 20 Sept., 1967, Mesa, Arizona

* ARTHUR GELDMACHER
  b: 3 April, 1890, Chadwick, Illinois
  m: 24 Dec., 1910, Elgin, Illinois DIV. 1952
  HELEN HUBBARD
  b: 23 Nov., 1892, Elgin,. Illinois

** DOROTHY ESTELLA GELDMACHER
   b: 19 Sept., 1911, Elgin, Illinois
   m: 26 April, 1935, Elgin, Illinois
   MAXWELL GERALD SHUMAN
   b: 10 Sept., 1907, Goshen, Indiana

*** GERALD LEE SHUMAN
    b: 19 Feb., 1944, Elgin, Illinois
    m: 13 July, 1963, Elgin, Illinois
    DOROTHEA JEAN MILLER
    b: 15 July, 1945

**** LARRY WAYNE SHUMAN
     b: 5 June, 1964, New York

**** JOHN ROBERT SHUMAN
     b: 11 Aug., 1965, Elgin, Illinois

**** THOMAS ALYAN SHUMAN
     b: 5 March, 1975, Germany

** GLADYS JANE GELDMACHER
   b: 16 May, 1915, Elgin, Illinois
   m: 15 Feb., 1940, Elgin, Illinois
   LAWRENCE G. ANDREWS
   b: 13 Oct., 1915, Humboldt, Illinois

***  KAREN LEE ANDREWS
    b: 1 Nov., 1945, Elgin, Illinois
    m: 15 June, 1963
    WILLIAM E. COX

*** CAROL LYNN ANDREWS
    b: 1 Sept., 1948, Bay City, Michigan
    m: 8 Jan., 1967, Elgin, Illinois
    ROBERT DAVIS
    b: 13 Jan., 1947, Chicago, Illinois

**** ROBERT DAVIS
     b: 29 Aug., 1968, Milwaukee, Wisconsin

**** CHRISTENE DAVIS
     b: 27 Aug., 1971, Elgin, Illinois

**** STEVEN DAVIS
     b: 24 Oct., 1972, Elgin, Illinois

* RICHARD GELDMACHER
  b: 1 April, 1893, Chadwick, Illinois
  d: 15 June, 19448, Seattle, Washington
  m: 26 Aug., 1922, Chicago, Illinois
  DOLORES THAYER
  b: 14 Sept., 1903, Chicago, Illinois

* OTTO LEON GELDMACHER
  b: 7 Jan., 1896, Chadwick, Illinois
  m: 11 Aug., 1918, Rockford, Illinois
  MARGARET LENTZ GREEN
  b: 5 Dec., 1900, Nashville, Tennessee

** EARL LEON GELDMACHER
   b: 16 May, 1921, Detroit, Michigan
   m: 29 May, 1941
   REBECCA CHARLENE FOSTER
   b: 31 Jan., 1920, Mayfield, Kentucky
   m: 4 May, 1951
   HELEN SUE (HENDRICK) MONTGOMERY
   b: 28 Dec., 1924, Highland Park, Michigan

*** SUE ANNE MONTGOMERY GELDMACHER
    b: 11 Dec., 1944, Detroit, Michigan
    m: 20 July, 1964
    JOSEPH EUGENE THOMISEE
    b: 19 Oct., 1946, Colfax, Louisiana

**** SHERRY LYNN THOMISEE
     b: 4 Aug., 1965, Colfax, Louisiana

**** TRACEY RENEE THOMISEE
      b: 4 Dec., 1968, Houma, Louisiana

*** MICHAEL JOHN MONTGOMERY GELDMACHER
    b: 11 Feb., 1947, Detroit, Michigan
    m: 10 June, 1966
    CHRISTINE MARIE RAMSEY
    b: 13 Sept., 1947, Detroit, Michigan

**** MICHAEL JOHN GELDMACHER JR.
     b: 1 Jan., 1968, Detroit, Michigan

**** DOUGLAS ALAN GELDMACHER
     b: 29 June, 1970, Detroit, Michigan

*** ANDREA CAROL GELDMACHER
    b: 25 Dec., 1959, Detroit, Michigan

*** BRIAN EARL GELDMACHER
    b: 22 April, 1961, Detroit, Michigan

** JOYCE ISABEL GELDMACHER
   b: 28 Sept., 1922, Detroit, Michigan
   m: 3 June, 1944, Detroit, Michigan
   JAMES RUDOLPH RAETZ
   b: 11 Feb., 1923, Detroit, Michigan

*** JAMES EARL RAETZ
    b: 13 Aug., 1945, Detroit, Michigan
    m: 17 May, 1969, Detroit, Michigan
    PATRICIA ANN HUTTON
    b: 26 Nov., 1947, Detroit, Michigan

**** CYNTHIA RENEE RAETZ
     b: 4 Feb., 1971, Detroit, Michigan

**** RACHEL LYN RAETZ
     b: 13 April, 1975, Southfield, Michigan

*** THOMAS ALAN RAETZ
    b: 12 Jan., 1948, Detroit, Michigan
    m: 20 May, 1972, Southfield, Michigan
    LESLIE ALANE JOHNSON
    b: 15 Oct., 1948, Detroit, Michigan

*** DAVID ERNEST RAETZ
    b: 15 July, 1951, Detroit, Michigan
    m: 1 July, 1972, Farmington Hills, Michigan
    LINDA ANN DOUGHERTY
    b: 27 Oct., 1951, Highland Park, Michigan

*** DANIEL ARTHUR RAETZ
    b: 1 Oct., 1954, Detroit, Michigan

*** JOHN QUENTIN RAETZ
    b: 20 Nov., 1957, Detroit, Michigan

** JANET MAE GELDMACHER
   b: 13 April, 1932, Detroit, Michigan
   m: 12 March, 1956, Detroit, Michigan DIV. 1964
   JOHN DILLOW
   b: 6 March, 1928, Virginia

*** JERMAINE RENE DILLOW
    b: 21 June, 1959, Detroit, Michigan

*** JEFFREY SHAWN DILLOW
    b: 24 Sept., 1960, Detroit, Michigan

*** JENNIFER LYN DILLOW
    b: 7 Sept., 1962, Detroit, Michigan

** BETTY LOUISE GELDMACHER
   b: 17 Jan., 1935, Detroit, Michigan
   m: 25 July, 1953, Pearl Harbor, Hawaii
   ALASTAIR MARTIN
   b: 30 April, 1931, Detroit, Michigan

*** KURT DOUGLAS MARTIN
    b: 4 Oct., 1954, Detroit, Michigan

*** BRUCE ALAN MARTIN
    b: 2 March, 1956, Detroit, Michigan

*** PAMELA JEANNE MARTIN
    b: 26 May, 1959, Detroit, Michigan

*** HUGH RUSSELL MARTIN
    b: 17 April, 1964, Detroit, Michigan

*** ROSS ALASTAIR MARTIN
    b: 21 June, 1967, Detroit, Michigan

*** STEPHANIE LOUISE MARTIN
    b: 31 May, 1969, Detroit, Michigan

* MARION E. GELDMACHER
  b: 3 Feb., 1900, Chadwick, Illinois
  m: 11 April, 1925, Elgin, Illinois
  ROBERT M. COLEMAN
  b: 25 April, 1899, Milledgeville, Illinois

** LOIS ANN COLEMAN
   b: 8 Aug., 1928, Sterling, Illinois
   m: 27 May, 1951, Milledgeville, Illinois
   HARLON K. JENNINGS
   b: 20 March, 1925, Fitchville, Ohio

*** JEANNETTE LYNN JENNINGS
    b: 13 Jan., 1953, Ashland, Ohio

*** CAROL SUE JENNINGS
    b: 25 Nov., 1955, Norwalk, Ohio

*** ANN MARIE JENNINGS
    b: 21 Feb., 1960, Norwalk, Ohio

==== Descendants of Henry Jacob and Katherine Daehler

* LAURA MARIA DAEHLER
  b: 9 Feb., 1905, Fair Haven Township, Illinois
  m: 15 June, 1968, Chadwick, Illinois
  JOHN GEORGE DODEN
  b: 22 Nov., 1903, Fair Haven Township, Illinois
  d: 14 Sept., 1973, Savanna, Illinois

* VERNON CONRAD DAEHLER
  b: 12 Feb., 1908, Chadwick, Illinois
  m: 24 Dec., 1930, Milledgeville, Illinois
  ROSY FRIEDA ALBER
  b: 25 Sept., 1909, Chadwick, Illinois

** DELORED MARIE DAEHLER
  b: 2 April, 1934, Chadwick, Illinois
  m: 8 Jan., 1956, Chadwick, Illinois
  LAWRENCE IBEN
  b: 14 June, 1930, Sterling, Illinois

*** GARY BERNARD IBEN
    b: 12 July, 1957, Savanna, Illinois

*** CRAIG ALAN IBEN
    b: 11 July, 1959, Savanna, Illinois

*** SHARON SUE IBEN
    b: 23 Aug., 1963, Savanna, Illinois

*** AMY LYNN IBEN
    b: 28 Sept., 1967, Savanna, Illinois

** RONALD EUGENE DAEHLER
   b: 7 Feb., 1938, Chadwick, Illinois
   m: 16 Aug., 1958, Chadwick, Illinois
   JEANNETTE FRIEDERICH
   b: 19 Feb., 1937, Chadwick, Illinois

*** DEE ANN DAEHLER
    b: 5 Nov., 1960, Ames, Iowa

*** KAREN SUE DAEHLER
    b: 5 April, 1963, Ames, Iowa
    d: 6 April, 1963, Ames, Iowa

** MERVYN HENRY DAEHLER
   b: 13 Aug., 1942, Freeport, Illinois
   m: 20 June, 1965, Bedford, Iowa
   REBECCA TIMBERLAKE
   b: 5 April, 1942, St. Joseph, Missouri

*** JENNIFER KAY DAEHLER
    b: 27 Jan., 1969, Waukegan, Illinois

*** CHRISTINA CAROL DAEHLER
    b: 1 April, 1971, Waukegan, Illinois

*** DEBORAH SUZANNE DAEHLER
    b: 21 Aug., 1973, Waukegan, Illinois

** MARVIN WILLIAM DAEHLER
   b: 13 Aug., 1942, Freeport, Illinois
   m: 28 Aug., 1965, Maywood, Illinois
   JUNE KELSON
   b: 3 June, 1941, Chicago, Illinois

*** CURTIS CHRISTOPER DAEHLER
    b: 30 Oct., 1969, Northampton, Massachusetts

*** JOSHUA EVAN DAEHLER
    b: 7 March, 1973, Northampton, Massachusetts

*** RENEE ELLEN DAEHLER
    b: 7 Aug., 1974, Northampton, Massachusetts

* CLARA GOLDA EMMA DAEHLER
  b: 7 July, 1913, Fair Haven Township, Illinois
  m: 23 March, 1937, Fair Haven Township, Illinois
  HOWARD RAYMOND ETNYRE
  b: 30 July, 1908, Mt. Carroll, Illinois

** WILMA CAROL ETNYRE
   b: 25 Feb., 1940, Savanna, Illinois
   m: 12 Aug., 1962, Chadwick, Illinois
   J VERNE WOLFE
   b: 9 Aug., 1939, Beatrice, Nebraska

*** DAVID VERNE WOLFE
    b: 22 Oct., 1963, Freeport, Illinois

*** BRIAN JAMES WOLFE
    b: 7 March, 1967, Geneva, Illinois

*** DOUGLAS HOWARD WOLFE
    b: 28 May, 1970, Hazeltown, Pennsylvania

** DENNIS HOWARD ETNYRE
   b: 28 Aug., 1945, Savanna, Illinois
   m: 29 July, 1967, Sterling, Illinois
   DIANE LYNN DITTMAR
   b: 21 Aug., 1947, Savanna, Illinois

*** DEREK ALAN ETNYRE
    b: 8 Sept., 1968, Rockford, Illinois

*** DEREN DANIEL ETNYRE
    b: 4 Dec., 1971, Clinton, Iowa

** DARRELL GENE ETNYRE
   b: 3 Jan., 1949, Savanna, Illinois
   m: 6 July, 1974, Milledgeville, Illinois
   CINDY JANE DITTMAR
   b: 7 March, 1955, Sterling, Illinois

*** JASON CLIFFORD ETNYRE
    b: 27 March, 1975, Clinton, Iowa

* VELDA ANNA LIZZIE DAEHLER
  b: 24 Oct., 1916, Fair Haven Township, Illinois
  m: 26 May, 1938, Fair Haven Township, Illinois
  DONALD ELMER SMITH
  b: 25 Jan., 1915, Mt. Carroll, Illinois

** ALLEN LEE SMITH
   b: 14 June, 1939, Chadwick, Illinois
   m: 26 May, 1938, Fair Haven Township, Illinois
   KAY MARLENE WINTER
   b: 6 April, 1939, Galena, Illinois

*** ERIC LEE SMITH
    b: 12 Oct., 1958, Freeport, Illinois

*** MARY ANNETTE SMITH
    b: 23 April, 1963, Morrison, Illinois

** DWIGHT EUGENE SMITH
   b: 16 April, 1954, Savanna, Illinois
   m: 13 July, 1973, Sterling, Illinois
   SUSAN ELAINE METZ
   b: 14 Oct., 1954, Sterling, Illinois

==== Descendants of William C. and Anna K. Daehler

* GOLDA LOUISE DAEHLER
  b: 30 Aug., 1895, Chadwick, Illinois
  m: 7 Oct., 1920, St. Paul, Minnesota
  BERTICE WEBSTER ALLEN
  b: 5 Sept., 1894, Spring Valley, Minnesota
  d: 18 Feb., 1975, Spring Valley, Minnesota

** LEOTA ERMA ALLEN
   b: 20 May, 1921, Spring Valley, Minnesota
   m: 16 Nov., 1939, Spring Valley, Minnesota
   RODNEY JOHN FIMON
   b: 30 March, 1920, Chatfield, Minnesota

*** RONALD JOHN FIMON
    b: 25 Aug., 1940, Spring Valley, Minnesota
    m: 26 June, 1960, Austin, Minnesota
    JULY ARLENE ELAM
    b: 29 Aug., 1940, Austin, Minnesota

**** MARTIN JOSEPH FIMON
     b: 7 July, 1962, Austin, Minnesota

**** ROBERT LYNN FIMON
     b: 5 Nov., 1963, Northfield, Minnesota

**** DAVID SCOTT FIMON
     b: 10 Oct., 1965, Iowa Falls, Iowa

**** RENEE MICHELLE FIMON
     b: 25 Jan., 1968, Iowa Falls, Iowa

**** RICHARD DEAN FIMON
     b: 8 Sept., 1971, Iowa Falls, Iowa

*** ALLEN JOSEPH FIMON
    b: 21 Aug., 1941, Spring Valley, Minnesota
    m: 10 Oct., 1968, Austin, Minnesota
    NANCY KAY THORN
    b: 26 June, 1944, Austin, Minnesota

**** MICHELLE RENEE FIMON
     b: 13 July, 1969, Austin, Minnesota

**** MICHAEL ALLEN FIMON
     b: 7 Aug., 1970, Austin, Minnesota

**** MARAYE BERNADETTE FIMON
     b: 9 Nov., 1973, Austin, Minnesota

* FLORENCE MAE DAEHLER
  b: 27 Dec., 1896, Chadwick, Illinois
  d: 28 Dec., 1965, Waterloo, Iowa
  m: 24 Sept., 1916, Spring Valley, Minnesota
  FREDERICK WILLIAM LEE
  b: 26 June, 1890, Spring Valley, Minnesota

** EVELYN MARIE LEE
   b: 1 Feb., 1917, Racine, Minnesota
   m: 12 Nov., 1945
   ODA LESTER CARSON
   b: 26 Oct., 1901, Tama, Iowa

** KENNTH FREDERICK LEE
   b: 2 July, 1918, Spring Valley, Minnesota
   d: 23 Jan., 1975, Des Moines, Iowa
   m: 4 July, 1948, Waterloo, Iowa
   RUBY LAUREL ANDERSON
   b: 23 Oct., 1923, Ortonville, Minnesota
   m: 12 Aug., 1972, Waterloo, Iowa
   DARLENE TAYLOR

** MELVIN LAWRENCE LEE
   b: 16 Jan., 1920, Spring Valley, Minnesota
   m: 16 Aug., 1954, Austin, Minnesota
   EVALYN MADGE SHUFELT
   b: 12 March, 1919, Nashua, Iowa

*** DEBRA ANN LEE
    b: 21 June, 1955, Waterloo, Iowa
    m: 21 June, 1974, Fort Gordon, Georgia
    WOODROW WILLIAM GARDNER
    b: 10 March, 1956, Cincinnati, Ohio

** DELORES CATHRYN LEE
   b: 10 Nov., 1921, Frankfort Township, Minnesota
   m: 28 Aug., 1950, Anita, Iowa
   MAX WILLIAM KARNS
   b: 14 Aug., 1921, Anita, Iowa

** MARVIN WILLIS LEE
   b: 5 May, 1923, Spring Valley, Minnesota
   m: 21 Feb., 1943, Preson, Minnesota
   SHIRLEY E. DRINKALL
   b: 30 July, 1926, Spring Valley, Minnesota

*** JUANITA KAY LEE
    b: 10 Sept., 1947, Preston, Minnesota
    m: 1 June, 1968, Wterloo, Iowa
    CLINTON JAMES MONTEITH
    b: 22 Aug., 1944, La Porte City, Iowa

**** CORINNE KAY MONTEITH
     b: 17 Dec., 1973, Waterloo, Iowa

*** DAVID GENE LEE
    b: 18 Aug., 1949, Preson, Innesota
    m: 10 Aug., 1974, Wyoming, Iowa
    BRENDA SUE WALTERS
    b: 5 Dec., 1949, Anamosa, Iowa

**** CHAD DAVID LEE
     b: 19 Jan., 1975, Waterloo, Iowa

*** ELWIN DALE LEE
    b: 4 Oct., 1955, Preston, Minnesota

*** JAMES JAY LEE
    b: 24 Jan., 1957, Preson, Minnesota

*** CHARLES RAY LEE
    b: 25 Dec., 1966, Waterloo, Iowa

** SHIRLEY MAE LEE
   b: 28 Dec., 1928, Grand Meadow, Minnesota
   m: 20 Dec., 1947, Independence, Iowa
   VERL KENNETH JOHNSON
   b: 22 April, 1912, Winthrop, Iowa
   d: 3 March, 1968, Waterloo, Iowa

*** VERL KENNETH JOHNSON JR.
    b: 27 May. 1949, Inglewood, California
    m: 1 June, 1970, Waterloo, Iowa
    WANDA ROSE EILDERTS
    b: 2 April, 1951, Waterloo, Iowa

**** DANIEL ROSS JOHNSON
     b: 12 June, 1972, Long Beach, California
     d: 13 June, 1972, Long Beach, California

** MARLYS JEAN LEE
   b: 13 Dec., 1930, Spring Valley, Minnesota
   m: 21 Feb., 1948, Waterloo, Iowa
   ROBERT WILBUR LEHMAN
   b: 22 Sept., 1926, Waterloo, Iowa

*** GREGORY WARD LEHMAN
    b: 31 Aug., 1948, Lorain, Ohio

*** RICKY JAE LEHMAN
    b: 3 Oct., 1949, Waterloo, Iowa

*** STEVEN MARK LEHMAN
    b: 18 Aug., 1950, Waterloo, Iowa
    m: 11 Aug., 1973, Waterloo, Iowa
    DEBORAH ANN WILDES
    b: 8 Sept., 1951, Waterloo, Iowa

*** KEVIN RAY LEHMAN
    b: 8 May, 1957, Waterloo, Iowa

** JOYCE ELRAY LEE
   b: 9 March, 1934, Spring Valley, Minnesota
   m: 11 Feb., 1957, Dubuque, Iowa
   JERALD CLAYTON KNAPPLE
   b: 8 Oct., 1933, Waldenburg, Arkansas

*** RANDALL CLAYTON KNAPPLE
    b: 10 March, 1954, Iowa City, Iowa

*** ROBIN LEE KNAPPLE
    b: 2 Sept., 1955, Waterloo, Iowa
    m:
    MICHAEL LYNN COX
    b: 6 March, 1957, Fort Smith, Arkansas

*** RENEE LYNN KNAPPLE
    b: 22 June, 1957, Waterloo, Iowa

** LOIS JOAN LEE
   b: 20 June, 1937, Spring Valley, Minnesota
   d: 9 April, 1944, Rochester, Minnesota

** ROBERT EUGENE LEE
   b: 19 March, 1941, Spring Valley, Minnesota
   m: 31 Aug., 1964, Preston, Minnesota
   JANET KAYE BEIER
   b: 17 April, 1945, Waterloo, Iowa

*** CINDY KAYE LEE
    b: 29 May, 1964,. Waterloo, Iowa

*** CATHY JO LEE
    b: 25 April, 1967, Waterloo, Iowa

* IRVIN WILLIAM DAEHLER
  b: 13 Feb., 1899, Chadwick, Illinois
  d: 23 July, 1925, Waterloo, Iowa

* DELLA MINNIE DAEHLER
  b: 7 May, 1900, Chadwick, Illinois
  d: 23 July, 1925, Waterloo, Iowa
  m:
  CHESTER FRANCIS
  b: 6 March, 1899
  m: 6 Aug., 1930
  LEE EDWARD NESBIT
  b: 20 Sept., 1900, Des Moines, Iowa

** MERWIN FRANCIS
   b: 17 Feb., 1921, St. Paul, Minnesota

** KATHRYN HELEN FRANCIS
   b: 21 Aug., 1922
   m: 7 Aug., 1937
   CHARLES E. ROBERTS
   b: 13 March, 1910

*** JANICE KAY ROBERTS
    b: 30 July, 1938

*** VICKI LYNN ROBERTS
    b: 20 Jan., 1952

** ELAINE DELLA FRANCIS
   b: 3 Nov., 1923
   m: 4 Oct., 1942
   EDWARD E. GORDON
   b: 11 Dec., 1916

*** TOBY ANN GORDON
    b: 8 Jan., 1944, Oakland, Califoria
    m:
    CHARLES B. JONES

**** JOHN CHARLES JONES
     b: 13 Feb., 1964, Oakland, California

**** CARRIE ANN JONES
     b: 13 Oct., 1968, Oakland, California

*** JOAN SUSAN GORDON
    b: 11 July, 1947, Oakland, California
    m:
    PATRICK J. MCQUOWN

*** JULIE KAY GORDON
    b: 4 May., 1953, Oakland, California

*** EDWARD DANIEL GORDON
    b: 31 Oct., 1962, Oakland, California

** LYLE NEIL FRANCIS
   b: 27, Sept., 1925
   d: 11 June, 1944, Saipan

** DARLENE MAE FRANCIS
   b: 4 Jan., 1927

* RAYMOND CHARLES DAEHLER
  b: 16 Aug., 1902, Chadwick, Illinois
  d: 21 Aug., 1936, Waterloo, Iowa
  m: 16 Jan., 1922, Chapin, Iowa
  GAYLE VELMA SWITZER
  b: 16 Dec., 1902, Chapin, Iowa
  d: 8 Oct., 1967, Waterloo, Iowa

** BETTY JEAN DAEHLER
   b: 24 Sept., 1924, Geneva, Iowa
   m: 8 Oct., 1944, Waterloo, Iowa
   JAMES MERLE ZASTROW
   b: 5 June, 1918, Mitchell, Iowa

*** SCOTT JAMES ZASTROW
    b: 21 March, 1945, Waterloo, Iowa
    m: 3 May, 1969, Des Moines, Iowa
    LINDA BINGFORT
    b: 8 Jan., 1948, Carroll, Iowa

**** KELLY LYNN ZASTROW
     b: 4 Oct., 1969, Des Moines, Iowa

**** JAMES SCOTT ZASTROW
     b: 5 Jan., 1974, Des Moines, Iowa

*** RICHARD LYNN ZASTROW
    b: 8 Oct., 1948, Waterloo, Iowa

*** KIM ALLYN ZASTROW
    b: 9 Feb., 1956, Waterloo, Iowa

* MARION ALLEN DAEHLER
  b: 26 July, 1906, Chadwick, Illinois
  m: 1 May, 1947, Waterloo, Iowa
  EVELYN BERNICE HANSON
  b: 19 Dec., 1914, Waterloo, Iowa

* ERMA DOROTHY DAEHLER
  b: 22 Aug., 1907, Chadwick, Illinois
  m: 24 Oct., 1923
  HARRY G. WICKHAM
  b: 22 July, 1903, Iowa Falls, Iowa
  d: 13 June, 1945, Waterloo, Iowa
  m: 22 April, 1972, Las Vegas, Nevada
  HAROLD SLAUGHTER
  b: 16 May, 1908, Winthrop, Iowa

** KEITH WICKHAM
   b: 15 May, 1925
   m: 13 March, 1947
   GWEN TIBBITS
   b: 16 Nov., 1927

*** BRUCE ALAN WICKHAM
    b: 20 Aug., 1949

*** CRAIG SCOTT WICKHAM
    b: 16 Nov., 1951

*** DANIEL JOE WICKHAM
    b: 17 April, 1959

** DARRELL EUGENE WICKHAM
  b: 2 May., 1926
  m: 13 June, 1948, Waterloo, Iowa
  ZONA MARIE HEIDT
  b: 10 March, 1929, Carthage, South Dakota

*** TONY J. WICKHAM
    b: 31 Aug., 1955

*** TODD MARTIN WICKHAM
    b: 28 Jan., 1959

** DONNA M. WICKHAM
  b: 2 July, 1929, Waterloo, Iowa
  m: 23 Jan., 1949, Waterloo, Iowa
  GEORGE E. WADDELL SR.
  b: 10 April, 1930, Mason City, Iowa

*** GEORGE E. WADDELL JR.
    b: 10 July, 1950, Waterloo, Towa

*** REBECCA A. WADDELL
    b: 3 Nov., 1951, Waterloo, Iowa

*** DEBRA K. WADDELL
    b: 23 May., 1953, Waterloo, Iowa
    m: 2 Nov., 1973, Waterloo, Iowa
    DANIEL W. VAUGHN
    b: 3 Nov., 1951

** BEVERLY ANN WICKHAM
   b: 26 July, 1930
   m:
   JAMES RALPH MC NEIL

*** MICHAEL JAMES MC NEIL
    b: 9 Nov., 1949

* MERRILL CLAYTON DAEHLER
  b: 27 Oct., 1914, Spring Valley, Minnesota
  d: 13 April, 1937, Waterloo, Iowa

==== Descendants of Charles J. and Anna Maria Queckboerner

* LAURA QUECKBOERNER
  b: 18 Feb., 1896, Chadwick, Carroll County, Illinois
  m: 12 Feb., 1919, Lanark, Carroll County, Illinois
  LOUIS FREEMAN RAUSER
  b: 12 Dec., 1890, Mt. Carroll, Carroll County, Illinois
  d: 8 July, 1967, Sterling, Whiteside County, Illino

** DONALD CHARLES RAUSER
   b: 20 Dec., 1919, Mt. Carroll, Carroll County, Illinois
   m: 19 Dec., 1945, Chadwick, Carroll County, Illinois
   ELOISE REMMERS
   b: 16 Nov., 1924, Morrison, Whiteside County, Illinois

*** LARRY WAYNE RAUSER
    b: 5 Dec., 1946, Morrison, Whiteside County, Illinois
    m: 5 Aug., 1972, Rock Falls, Whiteside County, Illinois
    DIANE CARD
    b: 8 May, 1951, Rock Falls, Whiteside County, Illinois

**** DANIEL CHRISTIAN RAUSER
     b: 19 Jan., 1975

*** KATHY LYNN RAUSER
    b: 24 Oct., 1948, Morrison, Whiteside County, Illinois
    m: 15 June, 1969, Morrison, Whiteside County, Illinois
    GLEN VOGEL
    b: 7 March, 1948, Columbia, Pennsylvania

*** KENT DALE RAUSER
    b: 18 Aug., 1951, Morrison, Whiteside County, Illinois

** LYLE LEROY RAUSER
   b: 14 May, 1951, Morrison, Whiteside County, Illinois
   m: 15 April, 1961, Rockford, Illinois
   OPAL FAY ROBERTS
   b: 29 June, 1936, Tupelo, Mississippi

*** RANDY LEE RAUSER
    b: 19 Jan., 1964, Rockford, Illinois

*** LISA MARIE RAUSER
    b: 17 Aug., 1969, Rockford, Illinois

* ANNA QUECKBOERNER
  b: 24 Oct., 1901
  d: 29 Aug., 1921
  m: 12 April, 1921
  EDWARD OLSON

==== Descendants of Conrad John and Hazel Daehler

* ENGAR DAEHLER
  b: 31 May, 1911
  m: 24 June, 1929
  MAX DOSS
  b: 17 March, 1889
  d: 9 Oct., 1949
  m: 18 May, 1952
  CARL HOCKHAUSEN
  b: 11 Oct., 1906

** MAXINE GRACE DOSS
   b: 19 March, 1930
   m: 14 April, 1950
   DONALD WILLIAM IMEL
   b: 6 Sept., 1923
   d: 14 Sept., 1964
   m: 14 Feb., 1971
   FRANCIS BARTZ
   b: 30 March, 1922

*** PENNIE SUE IMEL
    b: 18 Nov., 1952
    m: 1 Aug, 1970
    ANDREW WILLIAM HAMPTON
    b: 19 Nov., 1951

**** MAX WILLIAM HAMPTON
     b: 19 April, 1971

*** LONNIE WILLIAM IMEL
    b: 1 July, 1957

** VENITA HAZEL DOSS
   b: 20 Nov., 1935
   m: 21 July, 1957
   HUBERT ALLEN LUND
   b: 15 July, 1932
   d: 10 Dec., 1959
   m: 29 Oct., 1965
   GEORGE J. WELCH
   b: 14 May, 1924

* HENRY ELMER DAEHLER
  b: 5 Jan., 1915, Chadwick, Illinois
  m: 24 Oct., 1936
  CHRISTINE YAPPEN
  b: 24 May, 1918, Green Island, Iowa

** LONNA JEAN DAEHLER
   b: 21 Aug., 1940, Moline, Iowa
   m: 23 Feb., 1957, Maquoketa, Iowa
   GARY HERBERT SCHURBON
   b: 26 Feb., 1937, Andrew, Iowa

*** CINDY LEA SCHURBON
    b: 9 Aug., 1957, Maquoketa, Iowa

*** TAMMY KAY SCHURBON
    b: 27 April, 1960, Maquoketa, Iowa

*** MARY JO SCHURBON
    b: 2 Oct., 1962, Maquoketa, Iowa

*** SCOTT HENRY SCHURBON
    b: 18 Oct., 1964, Maquoketa, Iowa

*** LINDSAY RAE SCHURBON
    b: 12 Feb., 1975, Maquoketa, Iowa

** BETTY ANN DAEHLER
   b: 15 Sept., 1942, East Moline, Illinois
   m: 26 June, 1960, Maquoketa, Iowa
   DOUGLAS DWAIN MILLER
   b: 15 Aug., 1937, Maquoketa, Iowa

*** KRISTY KAY MILLER
    b: 7 Nov., 1961, Maquoketa, Iowa

*** KURTIS CHARLES MILLER
    b: 29 June, 1972, Iowa City, Iowa

** LARRY DEAN DAEHLER
   b: 15 April, 1946, Savanna, Illinois
   m: 30 June, 1963
   CAROLE GEHRKE
   b: 12 Sept., 1945, Dixon, Illinois

*** LARRY DAVID DAEHLER
    b: 26 Dec., 1963, Sterling, Illinois

*** JULIE RENEE DAEHLER
    b: 13 Aug., 1974, Sterling, Illinois

* GLADYS DAEHLER
  b: 8 Jan., 1917, Chadwick, Illinois
  m: 29 July, 1934, Shannon, Illinois
  VERLEN L. KUHLEMIER
  b: 9 March, 1911, Carroll County, Illinois

** GLEN RAY KUHLEMIER
   b: 23 Dec., 1934, Pearl City, Illinois
   m: 19 July, 1958, Freeport, Illinois
   DELORES LOUISE LINNEMAN
   b: 16 Aug., 1936, Freeport, Illinois

** MARVIN GENE KUHLEMIER
   b: 17 Nov., 1936, Milledgeville, Illinois
   m: 3 Oct., 1959, Rock Falls, Illinois
   BARBARA OTTENHAUSEN
   b: 2 Feb., 1939, Freeport, Illinois

*** THERESA KUHLEMIER
    b: 7 Sept., 1960, Sterling, Illinois

*** GENE KUHLEMIER
    b: 3 Sept., 1965, Sterling, Illinois

** EVAN DON KUHLEMIER
   b: 3 Sept., 1965, Sterling, Illinois
   m: 24 Oct., 1959, Rock Falls, Illinois
   JERRIE SHANKEL
   b: 14 Oct., 1937, Bloomington, Illinois

*** TERRIE LYNN KUHLEMIER
    b: 18 Oct., 1960, Sterling, Illinois
    d: 20 Oct., 1960, Sterling, Illinois

*** PATRICIA ANN KUHLEMIER
    b: 13 Oct., 1962, Sterling, Illinois

*** KATHY JO KUHLEMIER
    b: 26 Aug., 1967, Sterling, Illinois

*** KEVIN DON KUHLEMIER
    b: 25 June, 1969, Sterling, Illinois

* WALTER G. DAEHLER
  b: 24 Dec., 1919
  m: 1940
  BERNETTA SHEPPARD
  b: 25 June, 1921
  d: 1968
  m: 6 Aug., 1949
  BETTY JANE TUTHILL
  b: 9 Dec., 1922

** RAMONA PAULINE DAEHLER
   b: 29 June, 1941
   m: 2 Oct., 1957
   ALLEN A. KEMP
   b: 26 Feb., 1939
   m: 3 Dec., 1971
   LYLE HOPKIN
   b: 24 Sept., 1913
   d: 11 Oct., 1973

*** LINDA ELIZABETH KEMP
    b: 17 June, 1958

*** ALLEN ALBERT KEMP
    b: 13 Dec., 1959

*** BENNY LEON KEMP
    b: 24 Nov., 1960

*** FLOYD MICHAEL HOPKIN
    b: 29 March, 1973

** NORMA LORRAINE DAEHLER
   b: 2 July, 1943
   m: 15 Aug., 1964
   DALE M. CASEY
   b: 5 Aug., 1943

*** KIMBERLY DOREEN CASEY
    b: 18 Feb., 1966

*** RHONDA MICHELE CASEY
    b: 8 May, 1970

** IOLA MAY DAEHLER
   b: 20 July, 1944
   m: 1 April, 1962
   GEORGE HARSTON
   b: 12 Feb., 1934

*** GEORGE ERWIN HARSTON
    b: 21 Nov., 1963

*** RAYMOND LEE HARSTON
    b: 20 May, 1965

*** MELVIN DEAN HARSTON
  b: 20 April, 1967
  d: 20 April, 1967

** MADONNA MARIE DAEHLER
   b: 13 Aug., 1947
   m: 13 Feb., 1965
   LEO HARRY ROBINSON
   b: 26 Aug., 1931

*** LEON RAY ROBINSON
    b: 2 Sept., 1965

*** KEVIN ALLEN ROBINSON
    b: 30 Aug., 1967

*** TAMMY SUE ROBINSON
    b: 4 March, 1970

*** MICHAEL EDWARD ROBINSON
    b: 5 Oct., 1974

** JOHN WALTER DAEHLER
   b: 26 April, 1950

** THOMAS CLAUDE DAEHLER
   b: 16 March, 1956
   m: 14 Sept., 1974
   DARCI GULLY
   b: 20 Aug., 1955

* LUELLA DAEHLER
  b: 23 March, 1921
  m: 7 April, 1937
  CARL HENRY DAY
  b: 5 Aug., 1913

** RONALD CARL DAY
   b: 28 July, 1938
   m: 30 July, 1956
   RUTH PITTS
   b: 19 June, 1938

*** MARY LOU DAY
    b: 14 May, 1957

*** CINDY DAY
    b: 25 April, 1958
    d: 23 April, 1967

*** RONALD CARL DAY JR.
    b: 15 Feb., 1960

** NORMAN GENE HOWARD DAY
   b: 21 Feb., 1940
   m: 21 Aug., 1959
   LINDA BONNER
   b: 18 Jan., 1944

*** LORI DAY
    b: 9 June, 1960

*** KELLY ELAINE DAY
    b: 22 May, 1962

*** TODD DAVIS DAY
    b: 16 Aug., 1966

** PATRICIA HAZEL DAY
   b: 4 May, 1943
   m: 4 July, 1958
   MARK CUNNINGHAM
   b: 7 Sept., 1942

*** MARK LEE CUNNINGHAM
    b: 7 July, 1959

*** BRYAN DOUGLAS CUNNINGHAM
    b: 27 July, 1960

*** NICHOLAS CARL CUNNINGHAM
    b: 27 Nov., 1963

*** PATRICK TODD CUNNINGHAM
    b: 17 Aug., 1965

*** CHRISTOPHER SCOTT CUNNINGHAM
    b: 8 May, 1968

* HAZEL DAEHLER
  b: 16 Nov., 1924, Chadwick, Illinois
  m: 2 Oct., 1943
  MARVIN WIGGERT
  b: 22 Jan., 1924, Buffalo Lake, Minnesota

** LLOYD WIGGERT
   b: 19 Aug., 1944, Hutchinson, Minnesota
   m: 29 May, 1965
   ALICE JOYCE HULBURT
   b: 27 April, 1944, Wheaton, Minnesota

*** WILLIAM WIGGERT
    b: 26 Feb., 1966, Olivia, Minnesota
    d: 26 Feb., 1966, Olivia, Minnesota

*** JUDD WIGGERT
    b: 29 Sept., 1967, Glencoe, Minnesota

*** LUKE WIGGERT
    b: 8 Oct., 1970, Glencoe, Minnesota

** IVAN WIGGERT
   b: 9 Feb., 1949, Glencoe, Minnesota
   m: 31 Aug., 1974
   MARGARET ANN KOZUBIK
   b: 10 Jan., 1947, Willmar, New York

* RALPH HAROLD DAEHLER
  b: 21 March, 1922
  m:
  SYLVIA BELL WHIPPLE
  b: 23 Oct., 1921

** GLORIA DIANE DAEHLER
   b: 16 Feb., 1940
   m:
   FRANCIS EDWARD RICHESON
   b: 27 March, 1937

*** CHRISTINE LYNN RICHESON
    b: 19 Nov., 1956
    m:
    STEVEN WILLIAM SCHWARTZ
    b: 14 Oct., 1948

**** WILLIAM FRANCIS SCHWARTZ
     b: 28 June, 1974

** DORIS JUNE DAEHLER
   b: 16 Feb., 1940

** JAMES LEE DAEHLER
   b: 2 May, 1944
   m:
   ROSEMARY ANN CONSTANTINO
   b: 18 Aug., 1948

*** JAMES LEE DAEHLER JR.
    b: 19 Aug., 1964

*** JAYSON DAMON DAEHLER
    b: 18 Nov., 1970

** DON LYNN DAEHLER
   b: 29 March, 1948
   m:
   CARMEN KAY COOK
   b: 29 Nov., 1949

*** TAMMY JO DAEHLER
    b: 1 Oct., 1966

*** RENEE MARIE DAEHLER
    b: 27 July, 1971

==== Descendants of Conrad and Emma Geisz

* IRENE MARIE GEISZ
  b: 2 July, 1906, Fair Haven Township, Illinois
  m: 16 Jan., 1929, Fair Haven Township, Illinois
  JENS ANDRESEN
  b: 3 Dec., 1899, Clinton, Iowa

** ARLISS ANDRESEN
   b: 17 March, 1930, Savanna, Illinois

** DARLENE ANDRESEN
   b: 23 Jan., 1934, York Township, Illinois
   m: 27 Aug., 1957, Chadwick, Illinois
   ROGER LADD
   b: 21 Aug., 1934, Farmington, Maine

*** JEFFREY LADD
    b: 27 Nov., 1958, Farmington, Maine

*** MICHAEL JON LADD
    b: 16 May, 1961, Farmington, Maine

*** BETH JANE LADD
    b: 5 May, 1965, Farmington, Maine

** HAROLD ANDRESEN
   b: 10 Jan., 1937, York. Township, Illinois
   m: 4 Aug., 1959, Platteville, Wisconsin
   MARILYN KAY BELLMEYER
   b: 13 April, 1937, Platteville, Wisconsin

*** RANDY RAY ANDRESEN
    b: 15 March, 1961, Morrison, Illinois

*** RODNEY JAY ANDRESEN
    b: 14 April, 1962, Morrison, Illinois

*** PAMELA KAY ANDRESEN
    b: 26 March, 1967, Morrison, Illinois

*** ALAN LEE ANDRESEN
    b: 1 April, 1971, Morrison, Illinois

** DORIS ANN ANDRESEN
   b: 12 Feb., 1940, York Township, Illinois
   d: 14 Oct., 1968, Chadwick, Illinois

* REUBEN GEISZ
  b: 30 May, 1910, Fair Haven Township, Illinois
  m: 22 Jan., 1935, Dixon, Illinois
  DOROTHY VOLZ
  b: 23 July, 1916, Fair Haven Township, Illinois

** KENNETH GEISZ
   b: 8 March, 1938, Dixon, Illinois
   m: 12 Jan., 1958, Lanark, Illinois
   DORIS EDWARDS
   b: 28 May, 1935, Lanark, Illinois

*** DEBORAH GEISZ
    b: 8 Aug., 1958, Freeport, Illinois

*** KENNETH IRVIN GEISZ
    b: 9 June, 1960, Freeport, Illinois

*** KIMBERLY ANN GEISZ
    b: 10 July, 1965, Freeport, Illinois

** GLORIA MAY GEISZ
   b: 13 May, 1942, Freeport, Illinois
   m: 10 Nov., 1963, Chadwick, Illinois
   NORMAN STEWART
   b: 1 July, 1941, Chadwick, Illinois

*** ELLEN RAE STEWART
    b: 12 March, 1967, Freeport, Illinois

*** NEIL NORMAN STEWART
    b: 23 March, 1971, Freeport, Illinois

** RICHARD LEE GEISZ
   b: 8 April, 1945, Freeport, Illinois
   m: 1 March, 1969, Chadwick, Illinois
   SUSAN WEIRSAMA
   b: 9 Sept., 1949, Lanark, Illinois

*** STEPHEN LOUIS GEISZ
    b: 30 Nov., 1971, Freeport, Illinois

*** ROBIN GEISZ
    b: 6 Feb., 1974, Freeport, Illinois

* CLARENCE JOHN GEISZ
  b: 24 March, 1916, Fair Haven Township, Illinois
  d: 20 Feb., 1917, Fair Haven Township, Illinois

=== Descendants of Louis C. and Anna E. Daehler

* FERDINAND DAEHLER
  b: 25 April, 1873, Chadwick, Illinois
  d: 3 March, 1938, Boone, Iowa
  m: 23 July, 1924, Newton, Iowa
  EFFIE LYDIA MAYTAG
  b: 23 Feb., 1890, Laurel, Iowa

** JOHN CARL DAEHLER
   b: 14 Nov., 1935, Cook County, Illinois

** DAVID EDWIN DAEHLER
   b: 7 Oct., 1937, Cook County, Illinois
   m: 8 June, 1957, Newton, Iowa
   NANCY ANN BRECKENRIDGE
   b: 7 March, 1939, Iowa City, Iowa

*** DIANNE LYNN DAEHLER
    b: 27 April, 1939, Iowa City, lowa

*** DAVID WILLIAM DAEHLER
    b: 30 June, 1961, Newton, Iowa

* MARIA ELIZABETH DAEHLER
  b: 13 Nov., 1874, Chadwick, Illinois
  d: 26 Feb., 1947, Sterling, Illinois
  m: 2 Sept., 1914, Chadwick, Illinois
  HENRY R. PARSONS
  b: 16 Nov., 1858, New York
  d: 18 April, 1942, Sterling, Illinois

* CARL DAEHLER
  b: 21 March, 1876, Chadwick, Illinois
  d: 16 Jan., 1941
  m: 19 Feb., 1902
  DORA A. K. SCHREINER
  b: 20 Jan., 1881
  d: 11 May, 1967

** LOUISA MARIE DAEHLER
   b: 11 Feb., 1905
   m: 12 June, 1937
   FAY HARRY REITZEL
   b: 25 Jan., 1915

*** DAEHLE R. REITZEL
    b: 20 April, 1941
    m: 26 Sept., 1960
    LOIS ANN STONE
    m: 26 Sept., 1966
    SHERRY REIN

**** DONNA RAE REITZEL
     b: 12 April, 1961

**** DARYL RICHARD REITZEE
     b: 30 May, 1962

**** RHONDA KAE REITZEL
     b: 16 Sept., 1966

**** TRISHA MARIE REITZEL
     b: 25 June, 1967

**** TERI JEAN REITZEL
     b: 9 Oct., 1968

** PAUL WILLIAM FERDINAND DAEHLER
   b: 9 Jan., 1907, Fair Haven Township, Illinois
   d: 28 Dec., 1972, Mount Carroll, Illinois
   m: 6 Feb., 1941, Mount Carroll, Illinois
   LEONA ALBERTINE SCHMIDT
   b: 11 May, 1912, Freedom Township, Illinois

*** DARLENE LEONA DAEHLER
    b: 8 July, 1943, Freeport, Illinois
    m: 19 Dec., 1964, Mount Carroll, Illinois
    WILLIAM BERNARDIN
    b: 21 March, 1943, Rock Falls, Illinois

**** MARK ANDREW BERNARDIN
     b: 11 Oct., 1968, Freeport, Illinois

*** DWAYNE PAUL DAEHLER
    b: 8 July, 1943, Freeport, Illinois
    m: 24 June, 1967, Estherville, Iowa
    MARCIA NELSON
    b: 28 Oct., 1945, Estherville, Iowa

*** MELVA JEAN DAEHLER
    b: 21 March, 1955, Freeport, Illinois

** LOUIS ALBERT DAEHLER
   b: 7 Sept., 1909, Chadwick, Illinois
   d: 21 May, 1975, Porterville, California
   m: 10 June, 1937, Chadwick, Illinois
   DOROTHY MAE WEAST
   b: 18 Dec., 1908, Polo, Illinois

*** MARILYN SUE DAEHLER
    b: 2 Oct., 1938, Freeport, Illinois
    m: 18 June, 1960, San Jose, California
    STANLEY GADWAY
    b: 10 Nov., 1936, North Platte, Nebraska

**** STANLEY DEAN GADWAY
     b: 1 April, 1965, San Jose, California

**** SCOTT DAVID GADWAY
     b: 30 Aug., 1968, San Jose, California

*** CAROL JEAN DAEHLER
    b: 6 Jan., 1942, Freeport, Illinois
    m: 9 Dec., 1969, Berne, Switzerland
    CLAUDE JEROME ELLISON
    b: 23 July, 1930, Springfield, Missouri

**** CLAUDIA BETH ELLISON
     b: 10 July, 1970, Nuremburg, Germany

**** AMY REBECCA ELLISON
     b: 7 May, 1973, Netherlands

*** ELAINE MAE DAEHLER
    b: 15 Feb., 1944, Freeport, Illinois
    m: 12 Sept., 1964, Glendale, California
    ROBERT GERALD BEGLEY
    b: 30 April, 1941, Marshall, Arkansas

**** ALLEN KEITH BEGLEY
     b: 29 Oct., 1967, Portersville, California

**** DONNA LYNN BEGLEY
     b: 16 June, 1970, Portersville, California

** ARTHUR FREDERICK DAEHLER
   b: 24 Nov., 1911
   d: 26 Aug., 1913

** HAROLD HENRY DAEHLER
   b: 23 Oct., 1918
   d: 11 Feb., 1966
   m: 21 June, 1941
   VIVA DARLENE EVERSOLL
   b: 14 Jan., 1922

*** MARY ANN DAEHLER
    b: 22 Aug., 1942
    m: 27 Oct., 1962
    LESTER J. ELDER
    b: 8 Oct., 1938

**** JANE ELIZABETH ELDER
     b: 22 Aug., 1964

**** JOHN LESTER ELDER
     b: 12 Nov., 1965

*** DAVID LEE DAEHLER
    b: 27 May, 1948
    m: 22 Jan., 1972
    NADINE RAE EHRICH
    b: 23 Feb., 1950

**** DONNAE ELIZABETH DAEHLER
     b: 13 Oct., 1974

*** DIANA LYNN DAEHLER
    b: 27 May, 1948
    m: 26 April, 1968
    WALTER EDISON HOLLAND
    b: 5 Oct., 1946

**** JOSHUA HAROLD HOLLAND
     b: 18 March, 1946

* GEORGE DAEHLER
  b: 26 Jan., 1878, Chadwick, Illinois
  d: 25 April, 1945, Chadwick, Illinois
  m:
  PEARL KIER
  b: 30 Dec., 1889, Banner City, Kansas
  d: 7 April, 1968, Charlotte, Iowa

** ALBERT DAEHLER
   b: 16 July, 1929, Sterling, Illinois
   m: 5 July, 1969, Sterling, Illinois
   PHYLLIS (ZIEGLER) FRIIS
   b: 14 March, 1927, Clinton, Iowa
   d: 20 May, 1970, Clinton, Iowa
   m: 30 Nov., 1973, Honolulu, Hawaii
   COLLETTE SHAW
   b: 4 Feb. , 1921, Clinton, Iowa

* WILHELMINA DAEHLER
  b: 14 Sept., 1880, Chadwick, Illinois
  d: 23 March, 1943, Chadwick, Illinois
  m: 29 Jan., 1902, Chadwick, Illinois
  WILLIAM F. FINK
  b: 6 Aug. , 1875, Chadwick, Illinois
  d: 29 Oct., 1954, Chadwick, Illinois

** Stillborn son

** ELMER CARL FINK
   b: 18 Aug., 1904, Chadwick, Illinois
   d: 8 June, 1948, Chadwick, Illinois
   m: 19 Dec., 1925, Chadwick, Illinois
   CORA FAE APPEL
   b: 21 March, 1904, Thomson, Illinois

*** ARNOLD FAE FINK
    b: 16 March, 1927, Chadwick, Illinois
    m: 13 Oct., 1946, Chadwick, Illinois
    JUNE KATHRYN MILLER
    b: 2 June, 1928, Chadwick, Illinois
    d: 2 Dec., 1957, Lanark, Illinois
    m: 26 June, 1959, Milledgeville, Illinois
    FAITH MARIE COLEMAN
    b: 16 April, 1930, Milledgeville, Illinois

**** JUDY ANN FINK
     b: 2 June, 1947, Sterling, Illinois
     m: 20 March, 1968, Lanark, Illinois
     DONALD L. DAMPMAN
     b: 7 March, 1946, Milledgeville, Illinois

***** RANDY LEE DAMPMAN
      b: 8 June, 1970, Sterling, Illinois

***** DARRELL JASON DAMPMAN
      b: 9 Oct., 1973, Sterling, Illinois

**** GERALD FAE FINK
     b: 2 Oct., 1948, Sterling, Illinois
     m: 22 Feb., 1968, Milledgeville, Illinois
     PENNY WARNER
     b: 10 Feb., 1950, Freeport, Illinois

***** MICHAEL JOHN FINK
      b: 16 Sept., 1968, Sterling, Illinois

***** RODNEY MARSHALL FINK
      b: 12 May, 1972, Sterling, Illinois

**** TED ARTHUR FINK
     b: 28 Jan., 1954, Sterling, Illinois
     m: 28 Dec., 1974
     RHODA LEE DUMBROES

**** DALE ROSS FINK
     b: 4 July, 1960, Sterling, Tllinois

*** VERNON ARTHUR FINK
    b: 5 Jan., 1931, Chadwick, Illinois
    m: 6 Jan., 1963, Sterling, Illinois
    CAROLLYN ELAINE SERGEANT
    b: 3 July, 1937, Peoria, Illinois

**** THOMAS ARTHUR FINK
     b: 14 March, 1967, Sterling, Illinois

** HAROLD JOHN FINK
   b: 8 Nov., 1908, Chadwick, Illinois

** LAURA ANNA FINK
   b: 28 Aug., 1916, Chadwick, Illinois
   m: 20 June, 1942, Chadwick, Illinois
   HERBERT RICHARD PATTON
   b: 23 July, 1916, Villa Grove, Illinois
   d: 9 May, 1971, Stockton, California

*** JUDITH ANN PATTON
    b: 29 April, 1945, Menlo Park, California
    m: 11 April, 1965, Sacramento, California
    GARY KAGEL
    b: 25 July, 1943, Sacramento, California

**** CARL RICHARD KAGEL
     b: 24 May, 1972, Sacramento, California

**** MICHELLE ANN KAGEL
     b: 12 Nov., 1973, Sacramento, California

* ALBERT HARTMAN DAEHLER
  b: 30 Jan., 1883, Chadwick, Illinois
  d: 27 July, 1947, Colorado Springs, Colorado
  m:
  MABLE C. LOWRY
  b: 7 March, 1884
  d: 9 Jan., 1923, Colorado Springs, Colorado
  m: 2 Sept., 1925, Colorado Springs, Colorado
  MARJORIE BARRON
  b: 15 July, 1902, Kirwin, Kansas

** ELISA DAEHLER
   b: 22 Dec., 1927, Colorado Springs, Colorado
   d: 23 Dec., 1960, Colorado Springs, Colorado

** MARY DAEHLER
   b: 19 Sept., 1930, Colorado Springs, Colorado
   m: 3 Oct., 1958, Castle Rock, Colorado
   JOHN HENRY SMITH
   b: 23 Feb., 1926, Malvery, Pennsylvania
   d: 28 July, 1969, Lincoln, Nebraska

* OSCAR DAEHLER
  b: 9 Nov., 1884, Chadwick, Illinois
  d: 13 Aug., 1959, Freeport, Illinois
  m: 25 June, 1912, Moose Jaw, Saskatchewan
  DORA STUART
  b: 3 Dec., 1884, Savanna, Illinois
  d: 2 May, 1944, Chadwick, Illinois

* FRED DAEHLER
  b: 24 Sept., 1887, Chadwick, Illinois
  d: 6 Jan., 1967, Chadwick, Illinois
  m: 25 March, 1917, Vandalia, Michigan
  GRACE RATLIFF
  b: 24 Nov., 1887, Fairmont, Indiana
  d: 13 March, 1946, Freeport, Illinois

* HERMAN WALTER DAEHLER
  b: 21 March, 1891, Chadwick, Illinois
  d: 16 March, 1962, Chadwick, Illinois
  m: 3 Jan., 1915, Chadwick, Illinois
  LOUISA STRAUCH
  b: 31 May, 1889, Chadwick, Illinois

** ELLWOOD WILLIAM DAEHLER
   b: 11 April, 1916, Chadwick, Illinois
   m: 9 Dec., 1967, Thomson, Illinois
   BESSIE RUTH GROHARING
   b: 8 July, 1912, Thomson, Illinois

** ARLOWE KENNETH DAEHLER
   b: 24 Sept., 1918, Chadwick, Illinois
   m: 11 June, 1950, Hartford, Wisconsin
   HAZEL DELORES LEPIEN
   b: 13 Oct., 1925, Hartford, Wisconsin

*** JOHN PAUL DAEHLER
    b: 11 Sept., 1954, Chicago, Illinois

*** SARA LOUISA DAEHLER
    b: 28 Sept., 1955, Sterling, Illinois

*** RUTH MARIE DAEHLER
    b: 15 Jan., 1958, Sterling, Illinois

** LYLE EUGENE DAEHLER
   b: 10 Dec., 1920, Chadwick, Illinois
   d: 3 March, 1931, Freeport, Illinois

** LEON CLAIRE DAEHLER
   b: 1 Feb., 1924, Chadwick, Illinois
   m: 30 Aug., 1953, Mount Carroll, Illinois
   MARILYN RUTH ERDMIER
   b: 3 Aug., 1932, Freeport, Illinois

*** JEFFREY LLOYD DAEHLER
    b: 6 Dec., 1954, Sterling,

*** CONNIE SUE DAEHLER
    b: 28 Feb., 1959, Sterling, Illinois

*** WILLIAM LEE DAEHLER
    b: 5 March, 1964, Morrison, Illinois

** EILEENE LOUISA DAEHLER
   b: 4 April, 1925, Chadwick, Illinois
   m: 30 June, 1951, Washington, D. C.
   WILLIAM NICHOLS BUTLER
   b: 17 Jan., 1927, Champaign, Illinois

*** JOSELYN GAIL BUTER
    b: 6 Oct., 1954, Alexandria, Virgina

*** SHAUNA LANI BUTLER
    b: 8 Feb., 1956, Honolulu, Hawaii

*** MARK JEREMY BUTLER
    b: 22 Aug., 1959, Honolulu, Hawaii

** DONOVAN CARL DAEHLER
   b: 28 March, 1928, Chadwick, Illinois
   m: 18 June, 1956, Sterling, Illinois
   JOYCE CATHERINE YELL
   b: 27 Aug., 1934, Sterling, Illinois

*** JO ANN LOUISA DAEHLER
    b: 16 April, 1957, Freeport, Illinois

*** KATHLEEN MARIE DAEHLER
    b: 30 Sept., 1958, Freeport, Illinois

*** JAMES DONOVAN DAEHLER
    b: 16 Sept., 1959, Freeport, Illinois

*** CHARLES HERMAN DAEHLER
    b: 27 Feb., 1964, Freeport, Illinois

* LOUISA LOUELLA DAEHLER
  b: 26 April, 1893, Chadwick, Illinois
  d: 6 Dec., 1931, Chadwick, Illinois
  m: 8 Dec., 1915, Chadwick, Illinois
  CARL HAAG
  b: 28 March, 1893
  d: 4 Aug., 1966

** ORVILLE GEORGE HAAG
   b: 6 Feb., 1923
   d: 26 Nov., 1962
   m: 26 July, 1957
   DORIS MEYER
