== Notes on the Dahler Ancestry

* JOHANNES DAEHLER served in the Austrian army, and then
  was in the Hessian governmental administrative service
  at Dieburg.

* ANNA MARIA (DAEHLER) SCHNAUFER was the widow of a
  district forest ranger. She received a pension and lived
  with her family on a large farm near Eifelsdorf.

* JACOB DAEHLER was born 3 Oct., 1752, near Wohnbach,
  Wetterau, Hesse; and died 5 Nov., 1831, at Freienseen,
  Hesse-Darmstadt. During the 1770's he saw military
  service in Holland and in the East Indies. Afterward
  he became a master carpenter. In the latter capacity
  he removed to Freienseen to assist in the building of
  a new church. There he married Anna Margretha Stein,
  who was born in Freienseen, 4 Sept., 1757; and died
  there, 4 April, 1828.

** PHILLIPINA DAEHLER married in 1806 a man named HUBER,
   who served as a soldier in Napoleon's army. She went
   with him to Italy. Later they returned to Germany.
   Her husband managed a dry goods and tailor shop in
   Strassburg.

** MARIA ELISA DAEHLER married PETER BACHMANN. They came
   to the United States in 1846 and settled near Albany,
   New York.

** ANNA MARIA DAEHLER married KONRAD SCHMIDT, who operated
   a bleaching, cotton weaving, and laundry business in
   or near Freienseen.

** ANNA MARGRETHA DAEHLER.

** KONRAD DAEHLER was a master carpenter in Freienseen.
   In 1854 he and his wife, whose maiden name was Boning,
   came with their family to the United States and
   settled in Chicago, Illinois. He died there ca. 1870.

** MARIA ELIZABETH DAEHLER.

** JOHANN KURT DAEHLER was born in Freienseen, 29 June,
   1788; and died there, 17 Dec., 1848. His trade was
   that of a master carpenter. His wife, whose maiden
   name was ANNA MARGRETHA BENZEL, was born in
   Freienseen, 24 Feb., 1791; and died there, 1 Nov. 1838.
   Her father, Johann Heinrich Benzel (born 15 Feb.,
   1754; died 23 March, 1828), was a tailor in Freienseen.
   Her mother was Anna Margretha (Bober) Benzel
   (born 11 Dec., 1757; died 26 Jan., 1814).

*** JOHANN KONRAD DAEHLER, born in Freienseen, 6 Feb., 1811.

*** JOHANNES DAEHLER, born in Freienseen, 6 Oct., 1817,
    died when nine months old.

*** KATHARINA DAEHLER, born in Freienseen, 6 Oct., 1817,
    was married in 1838 to CHRISTIAN LUTZ. They came to
    the United States and resided in Chicago, Illinois.

**** CHARLES LUTZ
**** GOTTLIEB LUTZ
**** LOUISA (LUTZ) KORETKE
**** MARIA (LUTZ) STUHL

* JOHANN HEINRICH JUNG was a baker in Freienseen. He was born
  14 March, 1763; and died in Freienseen, 14 Jan., 1835. His
  wife, whose maiden name was LOUISA MARGRETHA SCHMIDT, was
  born 16 June, 1778; and died near Freienseen, 28 July, 1848.

** DOROTHEA JUNG was the first wife of KONRAD IMMELT. She
   died in Freienseen of brain fever, 29 March, 1830. After
   her death her husband remarried. His eldest son by his
   second wife was OTTO IMMELT, who married WILHELMINA
   DAEHLER, daughter of JOHANN KONRAD DAEHLER.

** MARGRETHA JUNG was the wife of a shoemaker in Laubach.
   She died of a nervous affliction in 1837.

** ANNA ELISA JUNG married in 1836 HEINRICH VOLP,an oil
   merchant and farmer who resided near Freienseen.

** ELISABETHA JUNG married in 1836 LOUIS JOCHEM, a cooper
   and farmer who also resided near Freienseen.

** KATHARINA JUNG married in 1838 JOHANN KONRAD DAEHLER.

SOURCES:

* A SHORT VIEW OF THE DAEHLER ANCESTRY, a manuscript written
  in German by Johann Konrad Daehler, 1893; and translated by
  Albert H. Daehler, 1939.

* Research notes of Albert H. Daehler

* Genealogical data gleaned from the files of the Hessian
  State Archives at Darmstadt, Germany
