== Sources of Information

JOHANN KONRAD DAEHLER AND HIS FAMILY

[discrete]
=== Death notice of Johann Konrad Daehler

His death notice is copied from a contemporary
newspaper account. The clipping found in a scrap book
of family remembrances contains no identification as to
its source.

[discrete]
=== Family of Johann Konrad and Katharina Daehler

German data came from the manuscript autobiography of
Johann Konrad Daehler and from Freienseen parish
records contained in the files of the Hessian State
Archives at Darmstadt, Germany.

Marriage and burial records consulted in this
country were those contained in the registers of St.
Paul's German Lutheran Church, commonly known as the
Black Oak Church. It was located in Fair Haven Township
west of the village of Chadwick. Johann Konrad Daehler
helped to organize the church in 1860, and served as its
first duly elected secretary. The church ceased to
function as a church in 1950; and the church registers are
now part of the archives of the First Lutheran Church of
Chadwick.

Tombstone inscriptions have given valuable
clues. The older members of the Daehler family were
originally buried in the Daehler family cemetery that
was located on the homestead west of Chadwick. All of
the stones were removed and have been carefully reset
and preserved. At the same time, ca. 1910 or 1911, the
remains of those members of the family buried in the
private burial ground were exhumed and reinterred in the
Chadwick Cemetery. The family headstone contains the
following inscription in German:

[quote]
Burial place for the family of the legally
wedded couple, KONRAD AND KATHARINA DAEHLER, 1855
immigrants from Freienseen, Grand Duchy of Hesse, Germany.

Data about Otto and Wilhelmina (Daehler) Immelt
was obtained from the probate files (numbers 2380 and
2797) of the Black Hawk County, Iowa, District Court at
Waterloo. THE HISTORY OF BLACK HAWK COUNTY, IOWA,
published in Chicago by the Western Historical Company in
1878, contains on page 539 a short biographical sketch
of Otto Immelt, who at that time was farming in Bennington
Township near Waterloo. The couple had resided
there since 1867.

[discrete]
=== Children of Henry Jacob and Elisa Daehler/Wilhelmina Daehler

. Records of Jo Ann (Shimonek) Schiefelbein of Wichita,
  Kansas, who collected all data relating to the
  descendants of Charles and Dorothea (Daehler) Smith.

. Baptismal, confirmation, and burial records of St.
  Paul's German Lutheran Church, Chadwick, Illinois.
  Marriage records of Carroll County, Illinois, on
  file in office of the county clerk at Mt. Carrol.
  Burial records, Rosehill Cemetery, Chicago, Illinois.

. Family Bible records of Katharina (Daehler) Straub.
  THE HOLY BIBLE, published in Philadelphia by the A.J.
  Holman Company in 1882, is now in the possession of
  Mrs. Louis P. Roth (Myrene Clarke) of Princeton, Ill.

. Death certificates on file with the Bureau of Vital
  Statistics, Elgin, Illinois.

. Marriage records of Carroll County, Illinois.

. Family records, Mrs. John G. Doden (Laura Daehler)
  of Chadwick, Illinois.

. Family records, Mrs. B. W. Allen (Golda Daehler) of
  Spring Valley, Minnesota.

. Records of St. Paul's German Lutheran Church, Chadwick,
  Illinois.

. Family records, Henry E. Daehler of Maquoketa, Iowa,
  and Mrs. Verlen L. Kuhlemier (Gladys Daehler) of Rock
  Falls, Illinois.

. Records of St. Paul's German Lutheran Church, Chadwick,
  Illinois.

. Family records, Mrs. Jens Andresen (Irene Geisz) of
  Chadwick, Illinois.

[discrete]
=== Remaining Descendant Genealogies

Data about the various families came in the main
from information collected by the members of each
respective family. There are some exceptions. These relate to
those children of Louis C. and Anna E. Daehler who left no
descendants. In these instances it was necessary to obtain
data from church records, death certificates, death notices
in local newspapers, and reports given to the secretaries of
the Daehler family reunions, which have been held annually
Since 1934.
